### ISSUE TITLE
Future Bezel Engine games help

### ISSUE THREAD

**Issue by Mysticus92** [KillzXGaming/BEA-Library-Editor#3]
I'm trying to etract this latest version of the bea files, but it seems this tool made by you isn't compatible. Do you plan to update this tool?
[chara~pc01.nx.bea.zip](https://github.com/user-attachments/files/17349784/chara.pc01.nx.bea.zip)

**Comment by KillzXGaming** [comment]
Added https://github.com/KillzXGaming/BEA-Library-Editor/commit/4d07ea75a871e8cba8966691d1ab2d8b0c64b661
